/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controle.Controle;

public class TelaConfigurarPartida extends javax.swing.JFrame {

    Controle controle;
    
    public TelaConfigurarPartida(Controle controle) {
        this.controle = controle;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupJogadores = new javax.swing.ButtonGroup();
        buttonGroupDificuldade = new javax.swing.ButtonGroup();
        buttonGroupOperacao = new javax.swing.ButtonGroup();
        jLabelNumJogadores = new javax.swing.JLabel();
        jLabelDificuldade = new javax.swing.JLabel();
        jLabelOperacao = new javax.swing.JLabel();
        jRadioButtonUmJogador = new javax.swing.JRadioButton();
        jRadioButtonDoisJogadores = new javax.swing.JRadioButton();
        jRadioButtonFacil = new javax.swing.JRadioButton();
        jRadioButtonMedio = new javax.swing.JRadioButton();
        jRadioButtonDificil = new javax.swing.JRadioButton();
        jRadioButtonAdicao = new javax.swing.JRadioButton();
        jRadioButtonSubtracao = new javax.swing.JRadioButton();
        jRadioButtonMultiplicacao = new javax.swing.JRadioButton();
        jRadioButtonDivisao = new javax.swing.JRadioButton();
        jLabelVamosJogar = new javax.swing.JLabel();
        jLabelPartida = new javax.swing.JLabel();
        jButtonIniciar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNumJogadores.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelNumJogadores.setText("Número de Jogadores:");

        jLabelDificuldade.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelDificuldade.setText("Dificuldade da Partida:");

        jLabelOperacao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelOperacao.setText("Operação Matemática:");

        buttonGroupJogadores.add(jRadioButtonUmJogador);
        jRadioButtonUmJogador.setText("Um Jogador");
        jRadioButtonUmJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonUmJogadorActionPerformed(evt);
            }
        });

        buttonGroupJogadores.add(jRadioButtonDoisJogadores);
        jRadioButtonDoisJogadores.setText("Dois Jogadores");
        jRadioButtonDoisJogadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDoisJogadoresActionPerformed(evt);
            }
        });

        buttonGroupDificuldade.add(jRadioButtonFacil);
        jRadioButtonFacil.setText("Fácil");

        buttonGroupDificuldade.add(jRadioButtonMedio);
        jRadioButtonMedio.setText("Médio");

        buttonGroupDificuldade.add(jRadioButtonDificil);
        jRadioButtonDificil.setText("Difícil");

        buttonGroupOperacao.add(jRadioButtonAdicao);
        jRadioButtonAdicao.setText("(+)Adição");

        buttonGroupOperacao.add(jRadioButtonSubtracao);
        jRadioButtonSubtracao.setText("(-)Subtração");

        buttonGroupOperacao.add(jRadioButtonMultiplicacao);
        jRadioButtonMultiplicacao.setText("(x)Multiplicação");

        buttonGroupOperacao.add(jRadioButtonDivisao);
        jRadioButtonDivisao.setText("(/)Divisão");

        jLabelVamosJogar.setFont(new java.awt.Font("Dialog", 3, 58)); // NOI18N
        jLabelVamosJogar.setText("Vamos Jogar!");

        jLabelPartida.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabelPartida.setText("Deixe a partida do jeitinho que quiser!");

        jButtonIniciar.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jButtonIniciar.setText("Iniciar!");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVamosJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelDificuldade, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(jLabelNumJogadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelOperacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonUmJogador)
                                    .addComponent(jRadioButtonFacil)
                                    .addComponent(jRadioButtonAdicao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonSubtracao)
                                        .addGap(12, 12, 12)
                                        .addComponent(jRadioButtonMultiplicacao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonDivisao))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonMedio)
                                        .addGap(51, 51, 51)
                                        .addComponent(jRadioButtonDificil))
                                    .addComponent(jRadioButtonDoisJogadores))
                                .addGap(0, 35, Short.MAX_VALUE))))
                    .addComponent(jLabelPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVamosJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonUmJogador)
                    .addComponent(jRadioButtonDoisJogadores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonFacil)
                    .addComponent(jRadioButtonMedio)
                    .addComponent(jRadioButtonDificil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonAdicao)
                    .addComponent(jRadioButtonSubtracao)
                    .addComponent(jRadioButtonMultiplicacao)
                    .addComponent(jRadioButtonDivisao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        // Iniciar jogo com as configuracoes setadas
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void jRadioButtonDoisJogadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDoisJogadoresActionPerformed
        buttonGroupOperacao.clearSelection();
        jLabelOperacao.setVisible(false);
        jRadioButtonAdicao.setVisible(false);
        jRadioButtonSubtracao.setVisible(false);
        jRadioButtonMultiplicacao.setVisible(false);
        jRadioButtonDivisao.setVisible(false);
    }//GEN-LAST:event_jRadioButtonDoisJogadoresActionPerformed

    private void jRadioButtonUmJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonUmJogadorActionPerformed
        buttonGroupOperacao.clearSelection();
        jLabelOperacao.setVisible(true);
        jRadioButtonAdicao.setVisible(true);
        jRadioButtonSubtracao.setVisible(true);
        jRadioButtonMultiplicacao.setVisible(true);
        jRadioButtonDivisao.setVisible(true);
    }//GEN-LAST:event_jRadioButtonUmJogadorActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        new TelaPrincipalAreaAluno(controle).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDificuldade;
    private javax.swing.ButtonGroup buttonGroupJogadores;
    private javax.swing.ButtonGroup buttonGroupOperacao;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelDificuldade;
    private javax.swing.JLabel jLabelNumJogadores;
    private javax.swing.JLabel jLabelOperacao;
    private javax.swing.JLabel jLabelPartida;
    private javax.swing.JLabel jLabelVamosJogar;
    private javax.swing.JRadioButton jRadioButtonAdicao;
    private javax.swing.JRadioButton jRadioButtonDificil;
    private javax.swing.JRadioButton jRadioButtonDivisao;
    private javax.swing.JRadioButton jRadioButtonDoisJogadores;
    private javax.swing.JRadioButton jRadioButtonFacil;
    private javax.swing.JRadioButton jRadioButtonMedio;
    private javax.swing.JRadioButton jRadioButtonMultiplicacao;
    private javax.swing.JRadioButton jRadioButtonSubtracao;
    private javax.swing.JRadioButton jRadioButtonUmJogador;
    // End of variables declaration//GEN-END:variables
}
